services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    env_file:
      - config/.env
      - config/bazarr.env
    volumes:
      - ${ROOT_DIRECTORY}/config/bazarr:/config
      - ${ROOT_DIRECTORY}/data/media/movies:/data/media/movies
      - ${ROOT_DIRECTORY}/data/media/tv:/data/media/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    env_file:
      - config/.env
      - config/overseerr.env
    volumes:
      - ${ROOT_DIRECTORY}/config/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    env_file:
      - config/.env
      - config/plex.env
    volumes:
      - ${ROOT_DIRECTORY}/config/plex:/config
      - ${ROOT_DIRECTORY}/data/media/movies:/data/media/movies
      - ${ROOT_DIRECTORY}/data/media/tv:/data/media/tv
    ports:
      - 32400:32400
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    env_file:
      - config/.env
      - config/prowlarr.env
    volumes:
      - ${ROOT_DIRECTORY}/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - config/.env
      - config/radarr.env
    volumes:
      - ${ROOT_DIRECTORY}/config/radarr:/config
      - ${ROOT_DIRECTORY}/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - config/.env
      - config/sonarr.env
    volumes:
      - ${ROOT_DIRECTORY}/config/sonarr:/config
      - ${ROOT_DIRECTORY}/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    env_file:
      - config/.env
      - config/deluge.env
    volumes:
      - ${ROOT_DIRECTORY}/config/deluge:/config
      - ${ROOT_DIRECTORY}/data/torrents:/data/torrents
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
    restart: unless-stopped
